<?php
/*
 * ***********************************************************************************************************************
 * Copyright (c) 2015 OwlGaming Community - All Rights Reserved
 * All rights reserved. This program and the accompanying materials are private property belongs to OwlGaming Community
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Last updated by Maxime, 05-07-2015
 * ***********************************************************************************************************************
 */

include("header.php");
require_once './classes/TwoFactor.class.php';
$twofactor = new TwoFactor();
if (!$twofactor->is_two_factor_enabled() or $twofactor->is_two_factor_valid()) {
    header('Location: /');
    exit();
}
?>
<div id="main-wrapper">
    <div id="acc_info">
        <h2>Two-Factor Authentication</h2>
        <p>Your current IP address is not among the list of trusted IP addresses for this account.<br>Please enter a valid code generated by your Google Authenticator smartphone app.</p>
        <p>If you have lost your phone or can not access your Google Authenticator.<br>Please enter your Recovery Key provided to you when you set up two-factor authentication instead to remove this security measure.</p>
        <form method="post" action="/ajax/ajax_twofactor.php">
            <input type="hidden" id="step" name="step" value="validate_code">
            <table>
                <tr>
                    <td>
                        <b>Code Validation: </b>
                    </td>
                    <td>
                        <input id="code" name="code" maxlength="19" required="true" value="" style='width: 350px'>
                    </td>
                </tr>
            </table>
            <br>
            <input id="2factor_proceed" type="submit" value="Proceed">
        </form>
    </div>
    <div id="char_info_mid_top"></div>
    <div id="char_info_mid"></div>
    <div id="char_info">
        <p>&nbsp;</p>
    </div>
</div>
<div class="content_wrap">
    <div class="text_holder">
        <div class="features_box">

        </div>	
        <?php
        include("sub.php");
        include("footer.php");
        ?>
